# Generated by Django 3.2.6 on 2021-08-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('parent_uuid', models.UUIDField()),
                ('type', models.CharField(max_length=20)),
                ('name', models.TextField()),
                ('meta', models.JSONField()),
                ('data', models.JSONField()),
                ('modified', models.DateTimeField()),
            ],
        ),
    ]
