# Generated by Django 3.2.6 on 2021-08-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0002_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='meta',
            field=models.TextField(),
        ),
    ]
